name = "gmail-attachment-extractor"
main = "dist/src/index.js"
compatibility_date = "2024-06-04"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

# Custom domain
routes = [
  { pattern = "gmail-attachment-extractor.hirefrank.com/*", zone_name = "hirefrank.com" }
]

# Production variables
[vars]
LOG_LEVEL = "warn"
ENVIRONMENT = "production"

# Production KV Namespace
[[kv_namespaces]]
binding = "STORAGE"
id = "6477ceccc84c496898355abca55b676f"

# Production cron trigger - Every Sunday at midnight UTC
# Try Sunday as "SUN" instead of "0" to avoid ambiguity
[triggers]
crons = ["0 0 * * SUN"]

