name = "gmail-attachment-extractor"
main = "dist/src/index.js"
compatibility_date = "2024-06-04"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

# Custom domain
routes = [
  { pattern = "gmail-attachment-extractor.hirefrank.com/*", zone_name = "hirefrank.com" }
]

# Production variables
[vars]
LOG_LEVEL = "debug"
ENVIRONMENT = "production"
DRIVE_FOLDER_ID = "1iuEoIWKIWAdfKRpX0hxvhJRQQMMp0emc"
# DEBUG_MODE should be set as a secret for security

# Production KV Namespace
[[kv_namespaces]]
binding = "STORAGE"
id = "6477ceccc84c496898355abca55b676f"

# Production cron triggers
# - Every Sunday at midnight UTC
# - First day of every month at midnight UTC
[triggers]
crons = ["0 0 * * SUN", "0 0 1 * *"]

# Observability
[observability]
enabled = true

