name = "gmail-attachment-extractor"
main = "src/index.ts"
compatibility_date = "2024-01-01"
node_compat = true

# Environment variables (to be set in CloudFlare dashboard or .dev.vars file)
# [vars]
# GOOGLE_CLIENT_ID = ""
# GOOGLE_CLIENT_SECRET = ""

# Cron trigger - Every Sunday at midnight UTC
[triggers]
crons = ["0 0 * * 0"]

# KV Namespace binding (to be updated with actual namespace ID)
[[kv_namespaces]]
binding = "STORAGE"
id = "YOUR_KV_NAMESPACE_ID"
preview_id = "YOUR_PREVIEW_KV_NAMESPACE_ID"

# Development environment settings
[env.development]
vars = { LOG_LEVEL = "debug" }